; [env:aaaa-my-esp32-n4]
[env:aaaa-my-esp32s3sm-n4r2]
platform = espressif32
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
; board = aaaa-my-esp32-n4
; board = aaaa-my-esp32c3-n4
board = aaaa-my-esp32s3sm-n4r2
framework = arduino
monitor_speed = 115200

